### ISSUE TITLE
Revisar problemas XLoader - Andino

### ISSUE THREAD

**Issue by pepeciavirella** [datosgobar/portal-base#127]

**Comment by lrromero** [comment]
Información pertinente:

**Comment by lrromero** [comment]
Información pertinente:
https://github.com/ckan/ckanext-xloader/issues/75

Cada vez que se edita un dataset, xloader vuelver a subir todos sus recursos. Es a raíz de un problema en ckan, que se resuelve en la versión 2.7.7 (que al momento de escribir esto, todavía no está taggeada). En portales más chicos, no impacta mucho en la performance. En el caso de datos.gob.ar que recibe una federación cada 4 horas, el problema es mucho más notorio
